# Generated by rust2rpm 27
%bcond check 1

%global crate vivid

Name:           rust-vivid
Version:        0.10.1
Release:        2%{?dist}
Summary:        LS_COLORS manager with multiple themes

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/vivid
Source:         %{crates_source}
Patch:          01-etcetera.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Generator for the LS_COLORS environment variable that controls the colorized
output of ls, tree, fd, bfs, dust and many other tools.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        Apache-2.0 OR MIT
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/vivid

%prep
%autosetup -v -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
